services:
  backend:
    build:
      context: ./SharpTamasy.Api
      dockerfile: Dockerfile
    container_name: sharptamasy-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/tasks.db
    volumes:
      - backend-data:/app/data

  frontend:
    build:
      context: ./sharptamasy-frontend
      dockerfile: Dockerfile
    container_name: sharptamasy-frontend
    ports:
      - "4200:4200"
    volumes:
    - ./sharptamasy-frontend:/app
    - /app/node_modules
    depends_on:
      - backend

volumes:
  backend-data:
