// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SharpTamasy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524182641_UpdateTaskInheritance")]
    partial class UpdateTaskInheritance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("BugTask", b =>
                {
                    b.HasBaseType("TaskItem");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("BugTasks", (string)null);
                });

            modelBuilder.Entity("FeatureTask", b =>
                {
                    b.HasBaseType("TaskItem");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("FeatureTasks", (string)null);
                });

            modelBuilder.Entity("BugTask", b =>
                {
                    b.HasOne("TaskItem", null)
                        .WithOne()
                        .HasForeignKey("BugTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureTask", b =>
                {
                    b.HasOne("TaskItem", null)
                        .WithOne()
                        .HasForeignKey("FeatureTask", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
